name: Deploy static content to Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and upload artifact
      run: |
        # Your build commands here...

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1  # Updated to the latest version
      with:
        path: ./path-to-your-artifact
